name: ${project.name}
version: ${project.version}
main: ${main.class}
author: ${author}
api-version: 1.13
commands:
  ila:
    description: ItemsLangAPI main command.
    usage: /<command>
    default: op